-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, sum(purchase_amount) from customer as Revenue
Group by Gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount 
from Customer where discount_applied = 'Yes' and purchase_amount >
(SELECT avg(purchase_amount) from customer)

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, round(avg(review_rating),2) as avg_review from Customer 
group by item_purchased
order by avg_review DESC
LIMIT 5

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

SELECT shipping_type, avg(purchase_amount) as average_purcahse_value from customer
where shipping_type in ('Express','Standard')
group by shipping_type

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.

SELECT subscription_status, 
count(customer_id) as total_customers,
sum(purchase_amount) as total_revenue,
round(avg(purchase_amount),2) as average_spend
from customer
group by subscription_status

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
								or
--   which top 5 prodcuts rely heavily on discount to get sold?                             

SELECT item_purchased, 
concat(round(100 *(SUM(CASE WHEN discount_applied = 'yes' THEN 1 ELSE 0 END)/count(*)),2),'%')
as Discount_rate
from customer 
group by item_purchased
Order by Discount_rate DESC
limit 5


-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

WITH Customer_Type as (
Select customer_id,
CASE
	WHEN previous_purchases = 1 THEN 'NEW'
    WHEN previous_purchases between 1 and 10 THEN "Returning"
    ELSE "Loyal"
    END
    As Customer_segment
    
from customer
)
SELECT Customer_segment, count(*) as Total_customer from Customer_Type
group by Customer_segment

-- Q8. What are the top 3 most purchased products within each category? 

select * from 
(SELECT item_purchased,category, COUNT(customer_id) as total_order, 
RANK() over (PARTITION BY category order by COUNT(customer_id) DESC ) as rnk
from customer 
group by item_purchased,category) a
where rnk <= 3


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT count(Customer_Id) as total_Customer, subscription_status  from customer
where previous_purchases >5 
group by subscription_status

-- Q10. What is the revenue contribution of each age group? 
SELECT age_group, sum(purchase_amount) as Revenue
FROM customer
group by age_group
Order by Revenue DESC


-- Q11. What is the percentage of revenue contribution of each age group? 

SELECT age_group,sum(purchase_amount) as total_Revenue, 
concat(100* sum(purchase_amount)/(select sum(purchase_amount) from customer),'%') as RevenuePercent
FROM customer
group by age_group
Order by RevenuePercent DESC


